baseURL = 'https://kalarani.github.io/'
languageCode = 'en-us'
title = "Kala's corner"
theme = 'archie'

[params]
	mode="dark"
	customcss=["css/first.css"]

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/kalarani"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://x.com/lkalarani"

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true
